include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - test/**.mocks.dart
    - lib/widgets/custom_rubber_bottom_sheet.dart
    - lib/*/*.g.dart
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  plugins:
    - custom_lint

linter:
  rules:
    - always_declare_return_types
    - omit_local_variable_types
    - await_only_futures
    - prefer_null_aware_operators
    - cancel_subscriptions
    - directives_ordering
    - prefer_single_quotes
    - always_use_package_imports
    - prefer_typing_uninitialized_variables
    - prefer_final_locals
    - prefer_final_fields
    - camel_case_types
    - prefer_equal_for_default_values
