name: stops_sg
description: A Flutter application that displays live bus timings for bus stops in Singapore

version: 0.9.0+20

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.1.0
  animations: ^2.0.2
  android_alarm_manager_plus: ^4.0.3
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  drift: ^2.15.0
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  flutter_bloc: ^8.0.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_nfc_kit: ^3.4.2 # ^3.2.0 causes release build to fail
  flutter_svg: ^2.0.9
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.1
  latlong2: ^0.9.0
  location: ^6.0.2
  path: ^1.8.0
  path_provider: ^2.0.0
  provider: ^6.0.1
  quick_actions: ^1.0.7
  rubber: ^1.0.1
  shared_preferences: ^2.0.9
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.20
  url_launcher: ^6.0.17
  dynamic_color: ^1.4.0
  collection: ^1.18.0
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  intl: ^0.19.0
  sqlite3: ^2.3.0
  http: ^1.2.0
  drift_flutter: ^0.2.1
  package_info_plus: ^8.1.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^3.0.0-dev.3
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  riverpod_generator: ^3.0.0-dev.3
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.3
  go_router_builder: ^2.7.1
  build_verify: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icon_foreground: "assets/images/icon/icon_fg.png"
  adaptive_icon_background: "assets/images/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/bus-stop.svg
    - assets/images/pin.svg
    - assets/images/pin-outline.svg
    - assets/images/icon/
    - assets/secrets.json
    - assets/maps/map_style_dark.json
